plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'me.dio'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Web e JPA (Estrutura principal do projeto)
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

	// REQUISITO DO SPRING BOOT 4 PARA O H2 LOCAL
	// O escopo 'developmentOnly' impede que o H2 seja empacotado para o Railway
	developmentOnly 'org.springframework.boot:spring-boot-h2console'
	developmentOnly 'com.h2database:h2'

	// Driver do PostgreSQL (Usado estritamente em produção no ambiente do Railway)
	runtimeOnly 'org.postgresql:postgresql'

	// Testes Automatizados
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.jar{
	manifest {
		attributes["Main-Class"] = "me.dio.Application"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
tasks.withType(JavaCompile) {
	options.compilerArgs << "-Xlint:deprecation"
}

